[package]
name = "map_editor"
version = "0.1.0"
edition = "2021"
authors = ["Jon Binney <jon.binney@gmail.com>"]

[dependencies]
bevy = { version = "0.9" }
bevy_rapier3d = { version = "0.19", features = [ "simd-stable", "debug-render" ] }
